// ─── DATA CONSTANTS ────────────────────────────────────────────────────────

export const BET_AMOUNT = 10;
export const BET_LOCK_MINUTES = 31;

export const IPL_SCHEDULE = [
  { num: 1,  date: 'March 28',  time: '7:30 PM', fixture: 'Royal Challengers Bengaluru vs Sunrisers Hyderabad' },
  { num: 2,  date: 'March 29',  time: '7:30 PM', fixture: 'Mumbai Indians vs Kolkata Knight Riders' },
  { num: 3,  date: 'March 30',  time: '7:30 PM', fixture: 'Rajasthan Royals vs Chennai Super Kings' },
  { num: 4,  date: 'March 31',  time: '7:30 PM', fixture: 'Punjab Kings vs Gujarat Titans' },
  { num: 5,  date: 'April 1',   time: '7:30 PM', fixture: 'Lucknow Super Giants vs Delhi Capitals' },
  { num: 6,  date: 'April 2',   time: '7:30 PM', fixture: 'Kolkata Knight Riders vs Sunrisers Hyderabad' },
  { num: 7,  date: 'April 3',   time: '7:30 PM', fixture: 'Chennai Super Kings vs Punjab Kings' },
  { num: 8,  date: 'April 4',   time: '3:30 PM', fixture: 'Delhi Capitals vs Mumbai Indians' },
  { num: 9,  date: 'April 4',   time: '7:30 PM', fixture: 'Gujarat Titans vs Rajasthan Royals' },
  { num: 10, date: 'April 5',   time: '3:30 PM', fixture: 'Sunrisers Hyderabad vs Lucknow Super Giants' },
  { num: 11, date: 'April 5',   time: '7:30 PM', fixture: 'Royal Challengers Bengaluru vs Chennai Super Kings' },
  { num: 12, date: 'April 6',   time: '7:30 PM', fixture: 'Kolkata Knight Riders vs Punjab Kings' },
  { num: 13, date: 'April 7',   time: '7:30 PM', fixture: 'Rajasthan Royals vs Mumbai Indians' },
  { num: 14, date: 'April 8',   time: '7:30 PM', fixture: 'Delhi Capitals vs Gujarat Titans' },
  { num: 15, date: 'April 9',   time: '7:30 PM', fixture: 'Kolkata Knight Riders vs Lucknow Super Giants' },
  { num: 16, date: 'April 10',  time: '7:30 PM', fixture: 'Rajasthan Royals vs Royal Challengers Bengaluru' },
  { num: 17, date: 'April 11',  time: '3:30 PM', fixture: 'Punjab Kings vs Sunrisers Hyderabad' },
  { num: 18, date: 'April 11',  time: '7:30 PM', fixture: 'Chennai Super Kings vs Delhi Capitals' },
  { num: 19, date: 'April 12',  time: '3:30 PM', fixture: 'Lucknow Super Giants vs Gujarat Titans' },
  { num: 20, date: 'April 12',  time: '7:30 PM', fixture: 'Mumbai Indians vs Royal Challengers Bengaluru' },
  { num: 21, date: 'April 13',  time: '7:30 PM', fixture: 'Sunrisers Hyderabad vs Rajasthan Royals' },
  { num: 22, date: 'April 14',  time: '7:30 PM', fixture: 'Chennai Super Kings vs Kolkata Knight Riders' },
  { num: 23, date: 'April 15',  time: '7:30 PM', fixture: 'Royal Challengers Bengaluru vs Lucknow Super Giants' },
  { num: 24, date: 'April 16',  time: '7:30 PM', fixture: 'Mumbai Indians vs Punjab Kings' },
  { num: 25, date: 'April 17',  time: '7:30 PM', fixture: 'Gujarat Titans vs Kolkata Knight Riders' },
  { num: 26, date: 'April 18',  time: '3:30 PM', fixture: 'Royal Challengers Bengaluru vs Delhi Capitals' },
  { num: 27, date: 'April 18',  time: '7:30 PM', fixture: 'Sunrisers Hyderabad vs Chennai Super Kings' },
  { num: 28, date: 'April 19',  time: '3:30 PM', fixture: 'Kolkata Knight Riders vs Rajasthan Royals' },
  { num: 29, date: 'April 19',  time: '7:30 PM', fixture: 'Punjab Kings vs Lucknow Super Giants' },
  { num: 30, date: 'April 20',  time: '7:30 PM', fixture: 'Gujarat Titans vs Mumbai Indians' },
  { num: 31, date: 'April 21',  time: '7:30 PM', fixture: 'Sunrisers Hyderabad vs Delhi Capitals' },
  { num: 32, date: 'April 22',  time: '7:30 PM', fixture: 'Lucknow Super Giants vs Rajasthan Royals' },
  { num: 33, date: 'April 23',  time: '7:30 PM', fixture: 'Mumbai Indians vs Chennai Super Kings' },
  { num: 34, date: 'April 24',  time: '7:30 PM', fixture: 'Royal Challengers Bengaluru vs Gujarat Titans' },
  { num: 35, date: 'April 25',  time: '3:30 PM', fixture: 'Delhi Capitals vs Punjab Kings' },
  { num: 36, date: 'April 25',  time: '7:30 PM', fixture: 'Rajasthan Royals vs Sunrisers Hyderabad' },
  { num: 37, date: 'April 26',  time: '3:30 PM', fixture: 'Gujarat Titans vs Chennai Super Kings' },
  { num: 38, date: 'April 26',  time: '7:30 PM', fixture: 'Lucknow Super Giants vs Kolkata Knight Riders' },
  { num: 39, date: 'April 27',  time: '7:30 PM', fixture: 'Delhi Capitals vs Royal Challengers Bengaluru' },
  { num: 40, date: 'April 28',  time: '7:30 PM', fixture: 'Punjab Kings vs Rajasthan Royals' },
  { num: 41, date: 'April 29',  time: '7:30 PM', fixture: 'Mumbai Indians vs Sunrisers Hyderabad' },
  { num: 42, date: 'April 30',  time: '7:30 PM', fixture: 'Gujarat Titans vs Royal Challengers Bengaluru' },
  { num: 43, date: 'May 1',     time: '7:30 PM', fixture: 'Rajasthan Royals vs Delhi Capitals' },
  { num: 44, date: 'May 2',     time: '7:30 PM', fixture: 'Chennai Super Kings vs Mumbai Indians' },
  { num: 45, date: 'May 3',     time: '3:30 PM', fixture: 'Sunrisers Hyderabad vs Kolkata Knight Riders' },
  { num: 46, date: 'May 3',     time: '7:30 PM', fixture: 'Gujarat Titans vs Punjab Kings' },
  { num: 47, date: 'May 4',     time: '7:30 PM', fixture: 'Mumbai Indians vs Lucknow Super Giants' },
  { num: 48, date: 'May 5',     time: '7:30 PM', fixture: 'Delhi Capitals vs Chennai Super Kings' },
  { num: 49, date: 'May 6',     time: '7:30 PM', fixture: 'Sunrisers Hyderabad vs Punjab Kings' },
  { num: 50, date: 'May 7',     time: '7:30 PM', fixture: 'Lucknow Super Giants vs Royal Challengers Bengaluru' },
  { num: 51, date: 'May 8',     time: '7:30 PM', fixture: 'Delhi Capitals vs Kolkata Knight Riders' },
  { num: 52, date: 'May 9',     time: '7:30 PM', fixture: 'Rajasthan Royals vs Gujarat Titans' },
  { num: 53, date: 'May 10',    time: '3:30 PM', fixture: 'Chennai Super Kings vs Lucknow Super Giants' },
  { num: 54, date: 'May 10',    time: '7:30 PM', fixture: 'Royal Challengers Bengaluru vs Mumbai Indians' },
  { num: 55, date: 'May 11',    time: '7:30 PM', fixture: 'Punjab Kings vs Delhi Capitals' },
  { num: 56, date: 'May 12',    time: '7:30 PM', fixture: 'Gujarat Titans vs Sunrisers Hyderabad' },
  { num: 57, date: 'May 13',    time: '7:30 PM', fixture: 'Royal Challengers Bengaluru vs Kolkata Knight Riders' },
  { num: 58, date: 'May 14',    time: '7:30 PM', fixture: 'Punjab Kings vs Mumbai Indians' },
  { num: 59, date: 'May 15',    time: '7:30 PM', fixture: 'Lucknow Super Giants vs Chennai Super Kings' },
  { num: 60, date: 'May 16',    time: '7:30 PM', fixture: 'Kolkata Knight Riders vs Gujarat Titans' },
  { num: 61, date: 'May 17',    time: '3:30 PM', fixture: 'Punjab Kings vs Royal Challengers Bengaluru' },
  { num: 62, date: 'May 17',    time: '7:30 PM', fixture: 'Delhi Capitals vs Rajasthan Royals' },
  { num: 63, date: 'May 18',    time: '7:30 PM', fixture: 'Chennai Super Kings vs Sunrisers Hyderabad' },
  { num: 64, date: 'May 19',    time: '7:30 PM', fixture: 'Rajasthan Royals vs Lucknow Super Giants' },
  { num: 65, date: 'May 20',    time: '7:30 PM', fixture: 'Kolkata Knight Riders vs Mumbai Indians' },
  { num: 66, date: 'May 21',    time: '7:30 PM', fixture: 'Gujarat Titans vs Chennai Super Kings' },
  { num: 67, date: 'May 22',    time: '7:30 PM', fixture: 'Sunrisers Hyderabad vs Royal Challengers Bengaluru' },
  { num: 68, date: 'May 23',    time: '7:30 PM', fixture: 'Lucknow Super Giants vs Punjab Kings' },
  { num: 69, date: 'May 24',    time: '3:30 PM', fixture: 'Mumbai Indians vs Rajasthan Royals' },
  { num: 70, date: 'May 24',    time: '7:30 PM', fixture: 'Kolkata Knight Riders vs Delhi Capitals' },
  { num: 71, date: 'May 26',    time: '7:30 PM', fixture: 'Royal Challengers Bengaluru vs Gujarat Titans' },
  { num: 72, date: 'May 27',    time: '7:30 PM', fixture: 'Sunrisers Hyderabad vs Rajasthan Royals' },
];

export const MISC_RESULTS = {
  DRAW:      'DRAW',
  CANCELLED: 'CANCELLED',
};

export const IPL_TEAMS = [
  'Chennai Super Kings',
  'Delhi Capitals',
  'Gujarat Titans',
  'Kolkata Knight Riders',
  'Lucknow Super Giants',
  'Mumbai Indians',
  'Punjab Kings',
  'Rajasthan Royals',
  'Royal Challengers Bengaluru',
  'Sunrisers Hyderabad',
];

export const TEAM_ACRONYMS = {
  'Chennai Super Kings': 'CSK',
  'Delhi Capitals': 'DC',
  'Gujarat Titans': 'GT',
  'Kolkata Knight Riders': 'KKR',
  'Lucknow Super Giants': 'LSG',
  'Mumbai Indians': 'MI',
  'Punjab Kings': 'PBKS',
  'Rajasthan Royals': 'RR',
  'Royal Challengers Bengaluru': 'RCB',
  'Sunrisers Hyderabad': 'SRH',
};

export const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

/** Shared select input style used by AddMatchModal */
export const selectStyle = {
  width: '100%',
  padding: '0.6rem 0.8rem',
  border: '1px solid var(--border)',
  borderRadius: '10px',
  fontFamily: 'inherit',
  fontWeight: 700,
  fontSize: '0.82rem',
  background: 'var(--surface)',
  color: 'var(--text)',
  cursor: 'pointer',
  appearance: 'auto',
};
